CREATE TABLE CADASTRO ( /* CADASTRO*/
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME_COMPLETO VARCHAR
(255) NOT NULL,
    EMAIL VARCHAR
(255) UNIQUE NOT NULL,
    CPF VARCHAR
(11) NOT NULL,
    TELEFONE VARCHAR
(19),
    SENHA VARCHAR
(255) NOT NULL,
    REPETE_SENHA VARCHAR
(255) NOT NULL
);

CREATE TABLE CADATRO_IMOVEL(/* CADASTRO DOS IMOVEIS*/
    ID_CADASTRO_IMOVEL int PRIMARY KEY AUTO_INCREMENT,
    TITULO_IMOVEL VARCHAR
(255),
    ENDERECO VARCHAR
(255),
    NUM_QUARTOS INT,
    NUM_BANHEIROS INT,
    NUM_VAGAS INT,
    VALOR_NOITE FLOAT,
    IMAGENS VARCHAR
(255),
    OBS VARCHAR
(255),

    );

CREATE TABLE IMOVEL(
    ID_IMOVEL INT PRIMARY KEY AUTO_INCREMENT,
    TITULO_IMOVEL VARCHAR
(255),
    ENDERECO VARCHAR
(255),
    NUM_QUARTOS INT,
    NUM_BANHEIRO INT,
    NUM_VAGAS INT, VALOR_NOITE FLOAT,
    OBS VARCHAR
(255),
    IMAGENS VARCHAR
(255)
    FOREIGN KEY
(TITULO_IMOVEL,ENDERECO, NUM_QUARTOS,NUM_BANHEIRO,NUM_VAGAS,VALOR_NOITE, OBS, IMAGENS) REFERENCES CADATRO_IMOVEL
(TITULO_IMOVEL,ENDERECO, NUM_QUARTOS,NUM_BANHEIRO,NUM_VAGAS,VALOR_NOITE,IMAGENS,OBS)
    );

CREATE TABLE LOGIN (/*LOGIN- FK EMAIL E SENHA*/
    ID_LOGIN INT PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR
(255) NOT NULL,
    SENHA VARCHAR
(255) NOT NULL,
    
FOREIGN KEY
(EMAIL, SENHA) REFERENCES CADASTRO
(EMAIL, SENHA)



);

