CREATE TABLE CADASTRO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME_COMPLETO VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    CPF CHAR(11) NOT NULL,
    TELEFONE VARCHAR(19),
    SENHA VARCHAR(255) NOT NULL,
    REPETE_SENHA VARCHAR(255) NOT NULL
);

CREATE TABLE CADASTRO_IMOVEL (
    ID_CADASTRO_IMOVEL INT PRIMARY KEY AUTO_INCREMENT,
    TITULO_IMOVEL VARCHAR(255),
    ENDERECO VARCHAR(255),
    NUM_QUARTOS INT,
    NUM_BANHEIROS INT,
    NUM_VAGAS INT,
    VALOR_NOITE FLOAT,
    IMAGENS VARCHAR(255),
    OBS VARCHAR(255)
);

CREATE TABLE IMOVEL(
    ID_IMOVEL INT PRIMARY KEY AUTO_INCREMENT,
    ID_CADASTRO_IMOVEL INT,
    FOREIGN KEY
(ID_CADASTRO_IMOVEL) REFERENCES CADASTRO_IMOVEL(ID_CADASTRO_IMOVEL)

);


CREATE TABLE LOGIN (
    ID_LOGIN INT PRIMARY KEY AUTO_INCREMENT,
    ID_CADASTRO INT,
    FOREIGN KEY
(ID_CADASTRO) REFERENCES CADASTRO(ID)
);