CREATE TABLE CADASTRO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME_COMPLETO VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    CPF CHAR(11) NOT NULL,
    TELEFONE VARCHAR(19),
    SENHA VARCHAR(255) NOT NULL,
    REPETE_SENHA VARCHAR(255) NOT NULL
);

CREATE TABLE CADASTRO_IMOVEL (
    ID_CADASTRO_IMOVEL INT PRIMARY KEY AUTO_INCREMENT,
    TITULO_IMOVEL VARCHAR(255),
    ENDERECO VARCHAR(255),
    NUM_QUARTOS VARCHAR(33),
    NUM_BANHEIROS VARCHAR(33),
    NUM_VAGAS VARCHAR(33),
    VALOR_NOITE VARCHAR(33),
	IMAGENS varchar(255),
    OBS VARCHAR(255),
    email VARCHAR(255),
    telefone varchar (19)
);




